#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Generate the `wide_ranges[]` table used by md4c-ansi's cp_width(): the set of
# Unicode codepoints that occupy two terminal columns. Emitted as a C include
# (a list of {lo,hi} CP_RANGE initializers) consumed by src/md4c-ansi.c.
#
# Wide = East Asian Wide/Fullwidth (from the Python build's Unicode database)
#        plus a small set of Emoji_Presentation=Yes ranges that are *not* East
#        Asian Wide (regional-indicator flags and a few stray pictographs) and
#        would otherwise be mis-measured as one column.
#
# Regenerate after a Unicode bump:
#     python3 scripts/gen-wcwidth-wide.py > src/md4c-wcwidth-wide.h
#
# The generated table only grows the covered set relative to hand-maintenance,
# so widths never regress for codepoints that were already wide.

import sys
import unicodedata as u

# Emoji_Presentation=Yes ranges whose East Asian Width is not W/F. unicodedata
# does not expose Emoji_Presentation, so these are listed explicitly; they are
# rendered two columns wide by terminals despite their EAW class.
EMOJI_PRESENTATION_EXTRA = [
    (0x03248, 0x0324F),  # circled numbers on black squares
    (0x1F1E6, 0x1F1FF),  # regional indicator symbols (flags)
    (0x1F93B, 0x1F93B),  # modern pentathlon
    (0x1F946, 0x1F946),  # rifle
    (0x1FA60, 0x1FA6D),  # xiangqi pieces
]


def wide_codepoints():
    cps = set()
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:      # surrogates
            continue
        if u.east_asian_width(chr(cp)) in ("W", "F"):
            cps.add(cp)
    for lo, hi in EMOJI_PRESENTATION_EXTRA:
        cps.update(range(lo, hi + 1))
    return cps


def to_ranges(cps):
    ranges = []
    it = sorted(cps)
    start = prev = it[0]
    for cp in it[1:]:
        if cp == prev + 1:
            prev = cp
        else:
            ranges.append((start, prev))
            start = prev = cp
    ranges.append((start, prev))
    return ranges


def main():
    ranges = to_ranges(wide_codepoints())
    out = sys.stdout
    out.write("/* Generated by scripts/gen-wcwidth-wide.py from Unicode %s. */\n"
              "/* Do not edit by hand; rerun the script after a Unicode bump. */\n"
              % u.unidata_version)
    for i in range(0, len(ranges), 4):
        chunk = ranges[i:i + 4]
        out.write("    " + ",".join("{0x%x,0x%x}" % (a, b) for a, b in chunk)
                  + ("," if i + 4 < len(ranges) else "") + "\n")


if __name__ == "__main__":
    main()
