/*
 * md4c-width.c - the display width of text in terminal columns
 *
 * Copyright (c) 2026 Pantelis Antoniou <pantelis.antoniou@konsulko.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * SPDX-License-Identifier: MIT
 */

#include <libfymd4c/libfymd4c-width.h>

/* Sorted [lo,hi] ranges of codepoints. */
typedef struct { unsigned lo, hi; } CP_RANGE;

/* Combining marks (Mn/Me) and zero-width format characters (no column each).
 * Generated by scripts/gen-wcwidth.py; regenerate after a Unicode bump. */
static const CP_RANGE zero_width_ranges[] = {
#include "md4c-wcwidth-zero.h"
};

/* East Asian Wide/Fullwidth + emoji-presentation ranges (two columns each).
 * Generated by scripts/gen-wcwidth-wide.py; regenerate after a Unicode bump. */
static const CP_RANGE wide_ranges[] = {
#include "md4c-wcwidth-wide.h"
};

static int
cp_range_contains(const CP_RANGE* ranges, int n, unsigned cp)
{
    int lo = 0, hi = n - 1;
    while(lo <= hi) {
        int mid = (lo + hi) / 2;
        if(cp < ranges[mid].lo)      hi = mid - 1;
        else if(cp > ranges[mid].hi) lo = mid + 1;
        else                         return 1;
    }
    return 0;
}

int
fymd_cp_width(unsigned int cp)
{
    if(cp == 0)
        return 0;
    if(cp < 0x20 || (cp >= 0x7f && cp < 0xa0))   /* C0 / C1 controls */
        return 0;
    if(cp < 0x0300)                               /* fast path: Latin etc. */
        return 1;
    if(cp_range_contains(zero_width_ranges,
                         (int)(sizeof(zero_width_ranges)/sizeof(zero_width_ranges[0])), cp))
        return 0;
    if(cp_range_contains(wide_ranges,
                         (int)(sizeof(wide_ranges)/sizeof(wide_ranges[0])), cp))
        return 2;
    return 1;
}

size_t
fymd_utf8_decode(const char* s, size_t len, unsigned int* cp)
{
    unsigned char c;

    if(len == 0) {
        *cp = 0;
        return 0;
    }

    c = (unsigned char) s[0];
    if(c < 0x80) {
        *cp = c;
        return 1;
    }
    if((c & 0xe0) == 0xc0 && len >= 2 && ((unsigned char) s[1] & 0xc0) == 0x80) {
        *cp = ((unsigned) (c & 0x1f) << 6)
            | ((unsigned char) s[1] & 0x3f);
        return 2;
    }
    if((c & 0xf0) == 0xe0 && len >= 3 && ((unsigned char) s[1] & 0xc0) == 0x80
       && ((unsigned char) s[2] & 0xc0) == 0x80) {
        *cp = ((unsigned) (c & 0x0f) << 12)
            | (((unsigned) ((unsigned char) s[1] & 0x3f)) << 6)
            | ((unsigned char) s[2] & 0x3f);
        return 3;
    }
    if((c & 0xf8) == 0xf0 && len >= 4 && ((unsigned char) s[1] & 0xc0) == 0x80
       && ((unsigned char) s[2] & 0xc0) == 0x80
       && ((unsigned char) s[3] & 0xc0) == 0x80) {
        *cp = ((unsigned) (c & 0x07) << 18)
            | (((unsigned) ((unsigned char) s[1] & 0x3f)) << 12)
            | (((unsigned) ((unsigned char) s[2] & 0x3f)) << 6)
            | ((unsigned char) s[3] & 0x3f);
        return 4;
    }

    /* Malformed or truncated: yield the lead byte so the caller advances. */
    *cp = c;
    return 1;
}

size_t
fymd_str_width(const char* s, size_t len)
{
    size_t i = 0, w = 0;
    unsigned int cp;

    if(s == NULL)
        return 0;
    if(len == (size_t) -1) {
        len = 0;
        while(s[len] != '\0')
            len++;
    }

    while(i < len) {
        i += fymd_utf8_decode(s + i, len - i, &cp);
        w += (size_t) fymd_cp_width(cp);
    }
    return w;
}
